#!/bin/bash

p=$(pidof mpd pipewire)
kill $p

mpd &
pipewire &
swaybg -i /home/kita/pix/wallpapers/$(echo "$(<currentwallpaper)") -m fill &
cd /usr/local/searxng-docker && docker compose up -d &
echo "ok"
