#!/bin/bash

p=$(pidof mpd pipewire)
kill $p

XDG_CURRENT_DESKTOP=sway
mpd &
pipewire &
swaybg -i /home/kita/pix/wallpapers/$(echo "$(<currentwallpaper)") -m fill &
wal -i "/home/kita/pix/wallpapers/$(echo "$(<currentwallpaper)")"
#cd /usr/local/searxng-docker && docker compose up -d &
echo "ok"
