#!/bin/bash
wallpaper=$(ls ~/pix | rofi -dmenu -i)
p=$(pidof swaybg)
kill $p
echo $wallpaper > /home/sn/.config/sway/currentwallpaper
[ $wallpaper -z ] || swaybg -i /home/sn/pix/wallpapers/$wallpaper -m fill
